version: '2'

services:
  db_server:
    restart: always
    image: f2hex/postgres
    container_name: redmine-db_server
    volumes:
      - /data/redmine/db:/var/lib/postgresql/data
    networks:
      - redmine

  app_server:
    restart: always
    image: f2hex/redmine
    container_name: redmine-app_server
    volumes:
      - /data/redmine/app/files:/usr/src/redmine/files
    networks:
      - redmine

  web_server:
    restart: always
    image: f2hex/nginx
    container_name: redmine-web_server
    ports:
      - "443:443"
    volumes:
      - /data/redmine/web/log:/var/log/nginx
    networks:
      - redmine

networks:
  redmine:
